### ISSUE TITLE
[Meta-issue] Upstreaming changes from custom fork

### ISSUE THREAD

**Issue by jaimergp** [conda/constructor#497]
I've been working on a constructor fork for several months now, which implements several open issues here as well as other features. I have some time now so I will begin to upstream those changes. I will use this issue to track progress:

- [x] conda_interface doesn't support alpha/beta/rc conda versions
  - PR: #496 
- [x] Improve PKG branding and signing
  - PR: #469  
- [x] Add signing for Windows installers
  - PR: #475  
- [x] Customization of installer options (conda init, add to PATH) - only relevant for `conda` distributions
  - PR: https://github.com/conda/constructor/pull/507 
- [x] Additional files (see #465)
  - PR: #500  
- [x] Multi environments (see #359)
  - PR: #509  
- [ ] Support for new menuinst
  - PR: #474

**Comment by jaimergp** [comment]
Hi @conda/constructor! I hope this tag works, I think it's the first we are using it!

This team was created to help maintain `constructor` and related tooling and I figured I could ask for a couple reviews in the PRs mentioned in the comment above. These changes have been part of the `napari` fork I've been maintaining for some months, so they should work quite ok, but maybe there are rough edges in some cases.

Anyway, I would be super happy if an extra pair of eyes could give it a read and tell me what they think.

**Comment by larsoner** [comment]
> These changes have been part of the napari fork I've been maintaining for some months, so they should work quite ok, but maybe there are rough edges in some cases.

@hoechenberger has also successfully used them in https://github.com/mne-tools/mne-installers for the last ~6 months so we have some evidence that things work. I'll take a look, @hoechenberger if you could look, too, that would be great!
