### ISSUE TITLE
Tracking issues relating to previous condarc files hampering installation

### ISSUE THREAD

**Issue by hmaarrfk** [conda/constructor#568]
### Summary

The goal here is to collect user stories of how previous condarc files are hampering the installation for users. I think generally, when you get an installer, you expect it to "work". But this is problematic since some commands are affected by the current .condarc in the global space.

I think many of these issues are resolved by: https://github.com/conda/constructor/pull/559

But there may still be something we can do help users get a working setup after they've installed their package. Maybe ask them if they want to delete the old condarc file and start new?

### Linked Issues & PRs

- [ ] https://github.com/conda-forge/miniforge/issues/347
- [ ] https://github.com/conda-forge/miniforge/issues/255
- [ ] https://github.com/conda-forge/miniforge/issues/298
