### ISSUE TITLE
Release 3.4.5

### ISSUE THREAD

**Issue by jaimergp** [conda/constructor#704]
### Summary

Placeholder for `constructor 3.4.5` release.

| Pilot | @jaimergp |
|---|---|
| Co-pilot | TBD |

### Tasks

[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/constructor/releases
[main]: https://github.com/AnacondaRecipes/constructor-feedstock
[conda-forge]: https://github.com/conda-forge/constructor-feedstock

#### The week before release week

- [x] Ensure release candidates are being successfully built
- [ ] Test release candidates
    

#### Release week

- [x] Create release PR (see [release process][process]) - https://github.com/conda/constructor/pull/707
- [x] [Publish release][releases]
- [X] Feedstocks
    - [X] Bump version & update dependencies/tests in [Anaconda, Inc.'s feedstock][main] - https://github.com/AnacondaRecipes/constructor-feedstock/pull/19
    - [x] Bump version & update dependencies/tests in [conda-forge feedstock][conda-forge] - https://github.com/conda-forge/constructor-feedstock/pull/71
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)
